### ISSUE TITLE
addPolygon() without color keyword

### ISSUE THREAD

**Issue by kvas7andy** [sbrodeur/evert#4]
Hi! Thank you for the soft. While "make" I had some problems, but eventually came up to even binding  C++ with python via pip. 
Afterwards tested on room.py and cube.py. Room.py is ok, but after "python cube.py"I  got this error: 
```

Traceback (most recent call last):
  File "cube.py", line 128, in <module>
    main()
  File "cube.py", line 49, in main
    room.addPolygon(poly, color=Vector3(0.5,0.5,0.5))
TypeError: addPolygon() got an unexpected keyword argument 'color'

```

**Comment by sbrodeur** [comment]
@kvas7andy can you change this line in Room.py:
```python
room.addPolygon(poly, color=Vector3(0.5,0.5,0.5))
```
to
```python
room.addPolygon(poly, Vector3(0.5,0.5,0.5))
```
and see if it works?
It seems using the keyword arguments are causing problems for some version of Python or SWIG.
I remember it happened once on CentOS 7, but not on the latest Ubuntu.
